### ISSUE TITLE
Can Add a option for get the nfts in case I no have collection smart contract by Thirdweb?

### ISSUE THREAD

**Issue by gadespc** [thirdweb-example/nft-staking-app#13]
Y try use moralis or alchemy for all the gets , but I'm lost, I don't know where to start modifying, or in which parts of the code to attack.
Can someone guide me?
Thank you!!

**Comment by NickeaBennett** [comment]
Are you referring to Thirdweb, moralis or alchemy?  This is a Thirdweb Repo!!!

**Comment by gadespc** [comment]
You're right, but what's hard for me is knowing which parts of the methods are the get to show the NFTs to Stakear in this particular APP...
Sorry but I'm just a junior.
TNKS

**Comment by NickeaBennett** [comment]
I think the best place to ask for help is here: https://discord.gg/gfjKfmKwXJ 
Also, Jarod did a whole walkthrough here: https://www.youtube.com/watch?v=6l_9hieFFcw&t=5s

I hope that helps.
