### ISSUE TITLE
Can't claim rewards

### ISSUE THREAD

**Issue by CopsGit** [thirdweb-example/nft-staking-app#27]
Always shows Not enough reward tokens.
I transferred ERC20 tokens to the staking contract address but didn't work properly. 

![image](https://user-images.githubusercontent.com/112567995/215852653-39555abe-d5db-4f5c-843d-fabd0c499f65.png)

**Comment by jarrodwatts** [comment]
Hey @CopsGit You now need to call the `depositRewardTokens` function.

Full guide available for you here: https://blog.thirdweb.com/guides/how-to-allow-users-to-stake-their-nfts-and-earn-rewards/
