### ISSUE TITLE
Add pre-loader for staked tokens

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-example/nft-staking-app#35]
I received a report about this and it looks like this and has a delay before showing the actual token asset.

![image](https://github.com/thirdweb-example/nft-staking-app/assets/15052701/e67814d8-a5a3-4dd9-81cf-9922e5a250a3)

**Comment by warengonzaga** [comment]
Hey @atharvadeosthale and @avneesh0612 can you take a look into this? Thank you!

**Comment by atharvadeosthale** [comment]
You can use SSR to achieve that. We don't use that in examples because these are meant to be basic. Using SSR to fetch NFTs would also increase page load times.
